#!/usr/bin/env python

#  Membertools, a basic set of tools for administering lists, by Martin Keegan

#  Copyright (C) 2013  Martin Keegan
#
#  This programme is free software; you may redistribute and/or modify
#  it under the terms of the Apache Software Licence v2.0

import sys
import ConfigParser
import oursql
import psycopg2
from decant import transfer_entries

def run(conf):
    upstream_hostname = conf.get('mysql', 'db_hostname')
    upstream_user = conf.get('mysql', 'db_user')
    upstream_passwd = conf.get('mysql', 'db_passwd')
    downstream_db_name = conf.get('postgres', 'db_name')

    downstream = psycopg2.connect(database=downstream_db_name)

    def transfer_table(table_config):
        upstream = oursql.connect(upstream_hostname, 
                                  upstream_user, 
                                  upstream_passwd,
                                  table_config['db_name'])

        return transfer_entries(upstream, downstream,
                         table_config["source_table"],
                         table_config["destination_table"],
                         table_config["column_mapping"],
                         table_config["source_key_column"],
                         table_config["destination_key_column"])

    transfers = [ 
        {
            "db_name": "yrs_cms_live",
            "source_table": "centres",
            "destination_table": "centres",
            "column_mapping": {
                "city": "city",
                "name": "name",
                "contactemail": "contactemail"
                },
            "source_key_column": "contactemail",
            "destination_key_column": "contactemail"
            },
        {
            "db_name": "rewiredstate_pyrocms_live",
            "source_table": "default_event_users",
            "destination_table": "people",
            "column_mapping": {
                "first_name":"name",
                "email": "email",
                "phone": "telno",
                "year(dob)": "birthyear"
                },
            "source_key_column": "email",
            "destination_key_column": "email"
            }
        ]

    [ transfer_table(t) for t in transfers ]

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print "Usage: gather configfile.ini"
        sys.exit(1)

    _, config_file = sys.argv

    conf = ConfigParser.ConfigParser()
    conf.read(config_file)
    run(conf)
