#!/usr/bin/env python

#  Membertools, a basic set of tools for administering lists, by Martin Keegan

#  Copyright (C) 2013  Martin Keegan
#
#  This programme is free software; you may redistribute and/or modify
#  it under the terms of the Apache Software Licence v2.0

import sys
import json
import ConfigParser
import oursql
import psycopg2
from decant import transfer_entries

def run(conf, transfers):
    upstream_hostname = conf.get('mysql', 'db_hostname')
    upstream_user = conf.get('mysql', 'db_user')
    upstream_passwd = conf.get('mysql', 'db_passwd')
    downstream_db_name = conf.get('postgres', 'db_name')

    downstream = psycopg2.connect(database=downstream_db_name)

    def transfer_table(table_config):
        upstream = oursql.connect(upstream_hostname, 
                                  upstream_user, 
                                  upstream_passwd,
                                  db=table_config['db_name'])

        return transfer_entries(upstream, downstream,
                         table_config["source_table"],
                         table_config["destination_table"],
                         table_config["column_mapping"],
                         table_config["source_key_column"],
                         table_config["destination_key_column"])

    [ transfer_table(t) for t in transfers ]

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print "Usage: gather configfile.ini transfers.json"
        sys.exit(1)

    _, config_file, transfers_file = sys.argv

    conf = ConfigParser.ConfigParser()
    conf.read(config_file)

    transfers_config = json.load(file(transfers_file))

    run(conf, transfers_config)
