#!/usr/bin/env python

#  Membertools, a basic set of tools for administering lists, by Martin Keegan

#  Copyright (C) 2013  Martin Keegan
#
#  This programme is free software; you may redistribute and/or modify
#  it under the terms of the Apache Software Licence v2.0

import sys
import ConfigParser
import oursql
import psycopg2
from decant import transfer_entries

def run(conf):
    upstream_user = conf.get('mysql', 'db_user')
    upstream_passwd = conf.get('mysql', 'db_passwd')
    
    downstream = psycopg2.connect(database='rewired_state')

    upstream = oursql.connect('127.0.0.1', upstream_user, upstream_passwd, 
                              db='yrs_cms_live')

    transfer_entries(upstream, downstream,
        'centres', 'centre', {
            "city": "city",
            "name": "name",
            "contactemail": "contactemail"
            },
                     'contactemail',
                     'contactemail')

    upstream = oursql.connect('127.0.0.1', upstream_user, upstream_passwd, 
                              db='rewiredstate_pyrocms_live')

    transfer_entries(upstream, downstream,
        'default_event_users', 'people', {
            "first_name":"name",
            "email": "email",
            "phone": "telno",
            "year(dob)": "birthyear"
            },
                     'email',
                     'email')

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print "Usage: gather configfile.ini"
        sys.exit(1)

    _, config_file = sys.argv

    conf = ConfigParser.ConfigParser()
    conf.read(config_file)
    run(conf)
