#!/usr/bin/env python

#  Membertools, a basic set of tools for administering lists, by Martin Keegan

#  Copyright (C) 2013  Martin Keegan
#
#  This programme is free software; you may redistribute and/or modify
#  it under the terms of the Apache Software Licence v2.0

import sys
import itertools
import json
import ConfigParser
from mailchimp import update_list
import rsdb

def name_tuple_from_string(name):
    if name is None:
        return (None, None)
    words = name.split()
    count = len(words)
    if 2 <= count:
        return (words[0], words[-1])
    if 1 == count:
        return (words[0], None)
    # 0 == count
    return (None, None)

def mailchimp_tuple_from_db(row):
    email, name = row
    first_name, last_name = name_tuple_from_string(name)
    return (email, first_name, last_name)

# this is NOT a full test for email address validity at all
def valid_email_address(details):
    address = details[0]

    if address is None:
        return False
    if ' ' in address:
        return False
    if '@' not in address:
        return False
    return True

def run(conf, mailing_lists):
    api_key = conf.get('mailchimp', 'api_key')
    database_name = conf.get('postgres', 'db_name')

    def sync_list(api_key, list_name, sql):
        people = rsdb.query(database_name, sql)
        list_data1 = itertools.imap(mailchimp_tuple_from_db, people)
        list_data2 = itertools.ifilter(valid_email_address, list_data1)

        update_list(api_key, list_name, 10, list_data2)

    def do_sync(ml_info):
        sync_list(api_key,
                  ml_info["mailing_list"],
                  ml_info["query"])

    [ do_sync(ml) for ml in mailing_lists ]

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print "Usage: sync_to_mc sync.ini mailing_lists.json"
        sys.exit(1)

    _, conf_file, ml_file = sys.argv

    conf = ConfigParser.ConfigParser()
    conf.read(conf_file)

    mailing_lists = json.load(file(ml_file))

    run(conf, mailing_lists)
